id: A9904374A
title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:14:45.114150
  last_modified_at: 2022-02-28 23:14:45.114157
